[project]
protostar-version = "0.13.0"
lib-path = "lib"
cairo-path = ["lib/cairo_contracts/src"]

[contracts]
SuperToken = ["src/tokens/ERC20x/SuperToken/SuperTokenImpl.cairo"]
Pool = ["src/pools/PoolImpl.cairo"]
Aqueduct = ["src/examples/aqueduct/AqueductImpl.cairo"]
TestAccount = ["src/utils/account/TestAccountImpl.cairo"]

[profile.devnet.project]
gateway-url = "http://127.0.0.1:5050/"
chain-id = 1536727068981429685321
