[profile.default]
src = 'contracts'
libs = ['lib']
solc_version = "0.8.35"
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200
remappings = [
    '@superfluid-finance/ethereum-contracts/contracts/=lib/ethereum-contracts/contracts/',
    '@superfluid-finance/solidity-semantic-money/src/=lib/solidity-semantic-money/src/',
    '@openzeppelin-v5/=lib/openzeppelin-contracts/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/']
out = 'build/foundry/out'
