indent: "    " # four spaces
dependencyTypes: ["!peer", "!resolutions"] # let us take care of the peer dependency resolutions by hand
sortAz: ["!scripts"] # we prefer to sort scripts by-hand, because sometimes it uses run-s pattern
semverGroups:
  - label: Use looser ranges for metadata and ethereum-contracts local packages
    dependencies:
      - "@superfluid-finance/metadata"
      - "@superfluid-finance/ethereum-contracts"
    range: "^"
versionGroups:
  - label: Pin stack-trace to the same version, since newer version starts to use ES module
    dependencies:
      - "stack-trace"
    pinVersion: "0.0.10"
