indent: "    " # four spaces
dependencyTypes: ["!peer", "!resolutions"] # let us take care of the peer dependency resolutions by hand
sortAz: ["!scripts"] # we prefer to sort scripts by-hand, because sometimes it uses run-s pattern
semverGroups:
  - range: "^" # we use looser ranges for metadata and ethereum-contracts local packages
    dependencies:
      - "@superfluid-finance/metadata"
      - "@superfluid-finance/ethereum-contracts"
