/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface SuperfluidInterface extends ethers.utils.Interface {
  functions: {
    "APP_WHITE_LISTING_ENABLED()": FunctionFragment;
    "CALLBACK_GAS_LIMIT()": FunctionFragment;
    "MAX_APP_LEVEL()": FunctionFragment;
    "NON_UPGRADABLE_DEPLOYMENT()": FunctionFragment;
    "getCodeAddress()": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "proxiableUUID()": FunctionFragment;
    "updateCode(address)": FunctionFragment;
    "getGovernance()": FunctionFragment;
    "replaceGovernance(address)": FunctionFragment;
    "registerAgreementClass(address)": FunctionFragment;
    "updateAgreementClass(address)": FunctionFragment;
    "isAgreementTypeListed(bytes32)": FunctionFragment;
    "isAgreementClassListed(address)": FunctionFragment;
    "getAgreementClass(bytes32)": FunctionFragment;
    "mapAgreementClasses(uint256)": FunctionFragment;
    "addToAgreementClassesBitmap(uint256,bytes32)": FunctionFragment;
    "removeFromAgreementClassesBitmap(uint256,bytes32)": FunctionFragment;
    "getSuperTokenFactory()": FunctionFragment;
    "getSuperTokenFactoryLogic()": FunctionFragment;
    "updateSuperTokenFactory(address)": FunctionFragment;
    "updateSuperTokenLogic(address)": FunctionFragment;
    "registerApp(uint256)": FunctionFragment;
    "registerAppWithKey(uint256,string)": FunctionFragment;
    "registerAppByFactory(address,uint256)": FunctionFragment;
    "isApp(address)": FunctionFragment;
    "getAppLevel(address)": FunctionFragment;
    "getAppManifest(address)": FunctionFragment;
    "isAppJailed(address)": FunctionFragment;
    "allowCompositeApp(address)": FunctionFragment;
    "isCompositeAppAllowed(address,address)": FunctionFragment;
    "callAppBeforeCallback(address,bytes,bool,bytes)": FunctionFragment;
    "callAppAfterCallback(address,bytes,bool,bytes)": FunctionFragment;
    "appCallbackPush(bytes,address,uint256,int256,address)": FunctionFragment;
    "appCallbackPop(bytes,int256)": FunctionFragment;
    "ctxUseAllowance(bytes,uint256,int256)": FunctionFragment;
    "jailApp(bytes,address,uint256)": FunctionFragment;
    "callAgreement(address,bytes,bytes)": FunctionFragment;
    "callAppAction(address,bytes)": FunctionFragment;
    "callAgreementWithContext(address,bytes,bytes,bytes)": FunctionFragment;
    "callAppActionWithContext(address,bytes,bytes)": FunctionFragment;
    "decodeCtx(bytes)": FunctionFragment;
    "isCtxValid(bytes)": FunctionFragment;
    "batchCall(tuple[])": FunctionFragment;
    "forwardBatchCall(tuple[])": FunctionFragment;
    "isTrustedForwarder(address)": FunctionFragment;
    "versionRecipient()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "APP_WHITE_LISTING_ENABLED",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "CALLBACK_GAS_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_APP_LEVEL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "NON_UPGRADABLE_DEPLOYMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCodeAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "initialize", values: [string]): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "updateCode", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "replaceGovernance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgreementClass",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgreementClass",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgreementTypeListed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAgreementClassListed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgreementClass",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mapAgreementClasses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addToAgreementClassesBitmap",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromAgreementClassesBitmap",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSuperTokenFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSuperTokenFactoryLogic",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateSuperTokenFactory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSuperTokenLogic",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerApp",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAppWithKey",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAppByFactory",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isApp", values: [string]): string;
  encodeFunctionData(functionFragment: "getAppLevel", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getAppManifest",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "isAppJailed", values: [string]): string;
  encodeFunctionData(
    functionFragment: "allowCompositeApp",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isCompositeAppAllowed",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "callAppBeforeCallback",
    values: [string, BytesLike, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callAppAfterCallback",
    values: [string, BytesLike, boolean, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "appCallbackPush",
    values: [BytesLike, string, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "appCallbackPop",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "ctxUseAllowance",
    values: [BytesLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "jailApp",
    values: [BytesLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "callAgreement",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callAppAction",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callAgreementWithContext",
    values: [string, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callAppActionWithContext",
    values: [string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "decodeCtx",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCtxValid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchCall",
    values: [{ operationType: BigNumberish; target: string; data: BytesLike }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "forwardBatchCall",
    values: [{ operationType: BigNumberish; target: string; data: BytesLike }[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isTrustedForwarder",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "versionRecipient",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "APP_WHITE_LISTING_ENABLED",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "CALLBACK_GAS_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_APP_LEVEL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "NON_UPGRADABLE_DEPLOYMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCodeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "updateCode", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "replaceGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgreementClass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgreementClass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAgreementTypeListed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAgreementClassListed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAgreementClass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mapAgreementClasses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToAgreementClassesBitmap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromAgreementClassesBitmap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSuperTokenFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSuperTokenFactoryLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSuperTokenFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSuperTokenLogic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerApp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAppWithKey",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAppByFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isApp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAppLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAppManifest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAppJailed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowCompositeApp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCompositeAppAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callAppBeforeCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callAppAfterCallback",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "appCallbackPush",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "appCallbackPop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ctxUseAllowance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "jailApp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "callAgreement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callAppAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callAgreementWithContext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callAppActionWithContext",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decodeCtx", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isCtxValid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batchCall", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forwardBatchCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isTrustedForwarder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "versionRecipient",
    data: BytesLike
  ): Result;

  events: {
    "AgreementClassRegistered(bytes32,address)": EventFragment;
    "AgreementClassUpdated(bytes32,address)": EventFragment;
    "AppRegistered(address)": EventFragment;
    "CodeUpdated(bytes32,address)": EventFragment;
    "GovernanceReplaced(address,address)": EventFragment;
    "Jail(address,uint256)": EventFragment;
    "SuperTokenFactoryUpdated(address)": EventFragment;
    "SuperTokenLogicUpdated(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AgreementClassRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AgreementClassUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "AppRegistered"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "CodeUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernanceReplaced"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Jail"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SuperTokenFactoryUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SuperTokenLogicUpdated"): EventFragment;
}

export type AgreementClassRegisteredEvent = TypedEvent<
  [string, string] & { agreementType: string; code: string }
>;

export type AgreementClassUpdatedEvent = TypedEvent<
  [string, string] & { agreementType: string; code: string }
>;

export type AppRegisteredEvent = TypedEvent<[string] & { app: string }>;

export type CodeUpdatedEvent = TypedEvent<
  [string, string] & { uuid: string; codeAddress: string }
>;

export type GovernanceReplacedEvent = TypedEvent<
  [string, string] & { oldGov: string; newGov: string }
>;

export type JailEvent = TypedEvent<
  [string, BigNumber] & { app: string; reason: BigNumber }
>;

export type SuperTokenFactoryUpdatedEvent = TypedEvent<
  [string] & { newFactory: string }
>;

export type SuperTokenLogicUpdatedEvent = TypedEvent<
  [string, string] & { token: string; code: string }
>;

export class Superfluid extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: SuperfluidInterface;

  functions: {
    APP_WHITE_LISTING_ENABLED(overrides?: CallOverrides): Promise<[boolean]>;

    CALLBACK_GAS_LIMIT(overrides?: CallOverrides): Promise<[BigNumber]>;

    MAX_APP_LEVEL(overrides?: CallOverrides): Promise<[BigNumber]>;

    NON_UPGRADABLE_DEPLOYMENT(overrides?: CallOverrides): Promise<[boolean]>;

    getCodeAddress(
      overrides?: CallOverrides
    ): Promise<[string] & { codeAddress: string }>;

    initialize(
      gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<[string]>;

    updateCode(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getGovernance(overrides?: CallOverrides): Promise<[string]>;

    replaceGovernance(
      newGov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerAgreementClass(
      agreementClassLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateAgreementClass(
      agreementClassLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isAgreementTypeListed(
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean] & { yes: boolean }>;

    isAgreementClassListed(
      agreementClass: string,
      overrides?: CallOverrides
    ): Promise<[boolean] & { yes: boolean }>;

    getAgreementClass(
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string] & { agreementClass: string }>;

    mapAgreementClasses(
      bitmap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string[]] & { agreementClasses: string[] }>;

    addToAgreementClassesBitmap(
      bitmap: BigNumberish,
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { newBitmap: BigNumber }>;

    removeFromAgreementClassesBitmap(
      bitmap: BigNumberish,
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { newBitmap: BigNumber }>;

    getSuperTokenFactory(
      overrides?: CallOverrides
    ): Promise<[string] & { factory: string }>;

    getSuperTokenFactoryLogic(
      overrides?: CallOverrides
    ): Promise<[string] & { logic: string }>;

    updateSuperTokenFactory(
      newFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateSuperTokenLogic(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerApp(
      configWord: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerAppWithKey(
      configWord: BigNumberish,
      registrationKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerAppByFactory(
      app: string,
      configWord: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isApp(app: string, overrides?: CallOverrides): Promise<[boolean]>;

    getAppLevel(appAddr: string, overrides?: CallOverrides): Promise<[number]>;

    getAppManifest(
      app: string,
      overrides?: CallOverrides
    ): Promise<
      [boolean, boolean, BigNumber] & {
        isSuperApp: boolean;
        isJailed: boolean;
        noopMask: BigNumber;
      }
    >;

    isAppJailed(app: string, overrides?: CallOverrides): Promise<[boolean]>;

    allowCompositeApp(
      targetApp: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isCompositeAppAllowed(
      app: string,
      targetApp: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    callAppBeforeCallback(
      app: string,
      callData: BytesLike,
      isTermination: boolean,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callAppAfterCallback(
      app: string,
      callData: BytesLike,
      isTermination: boolean,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    appCallbackPush(
      ctx: BytesLike,
      app: string,
      appAllowanceGranted: BigNumberish,
      appAllowanceUsed: BigNumberish,
      appAllowanceToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    appCallbackPop(
      ctx: BytesLike,
      appAllowanceUsedDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    ctxUseAllowance(
      ctx: BytesLike,
      appAllowanceWantedMore: BigNumberish,
      appAllowanceUsedDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    jailApp(
      ctx: BytesLike,
      app: string,
      reason: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callAgreement(
      agreementClass: string,
      callData: BytesLike,
      userData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callAppAction(
      app: string,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callAgreementWithContext(
      agreementClass: string,
      callData: BytesLike,
      userData: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    callAppActionWithContext(
      app: string,
      callData: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    decodeCtx(
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        [
          number,
          number,
          BigNumber,
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          string,
          string
        ] & {
          appLevel: number;
          callType: number;
          timestamp: BigNumber;
          msgSender: string;
          agreementSelector: string;
          userData: string;
          appAllowanceGranted: BigNumber;
          appAllowanceWanted: BigNumber;
          appAllowanceUsed: BigNumber;
          appAddress: string;
          appAllowanceToken: string;
        }
      ] & {
        context: [
          number,
          number,
          BigNumber,
          string,
          string,
          string,
          BigNumber,
          BigNumber,
          BigNumber,
          string,
          string
        ] & {
          appLevel: number;
          callType: number;
          timestamp: BigNumber;
          msgSender: string;
          agreementSelector: string;
          userData: string;
          appAllowanceGranted: BigNumber;
          appAllowanceWanted: BigNumber;
          appAllowanceUsed: BigNumber;
          appAddress: string;
          appAllowanceToken: string;
        };
      }
    >;

    isCtxValid(ctx: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

    batchCall(
      operations: {
        operationType: BigNumberish;
        target: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    forwardBatchCall(
      operations: {
        operationType: BigNumberish;
        target: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    versionRecipient(overrides?: CallOverrides): Promise<[string]>;
  };

  APP_WHITE_LISTING_ENABLED(overrides?: CallOverrides): Promise<boolean>;

  CALLBACK_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

  MAX_APP_LEVEL(overrides?: CallOverrides): Promise<BigNumber>;

  NON_UPGRADABLE_DEPLOYMENT(overrides?: CallOverrides): Promise<boolean>;

  getCodeAddress(overrides?: CallOverrides): Promise<string>;

  initialize(
    gov: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  proxiableUUID(overrides?: CallOverrides): Promise<string>;

  updateCode(
    newAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getGovernance(overrides?: CallOverrides): Promise<string>;

  replaceGovernance(
    newGov: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerAgreementClass(
    agreementClassLogic: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateAgreementClass(
    agreementClassLogic: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isAgreementTypeListed(
    agreementType: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isAgreementClassListed(
    agreementClass: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getAgreementClass(
    agreementType: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  mapAgreementClasses(
    bitmap: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string[]>;

  addToAgreementClassesBitmap(
    bitmap: BigNumberish,
    agreementType: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  removeFromAgreementClassesBitmap(
    bitmap: BigNumberish,
    agreementType: BytesLike,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getSuperTokenFactory(overrides?: CallOverrides): Promise<string>;

  getSuperTokenFactoryLogic(overrides?: CallOverrides): Promise<string>;

  updateSuperTokenFactory(
    newFactory: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateSuperTokenLogic(
    token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerApp(
    configWord: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerAppWithKey(
    configWord: BigNumberish,
    registrationKey: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerAppByFactory(
    app: string,
    configWord: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isApp(app: string, overrides?: CallOverrides): Promise<boolean>;

  getAppLevel(appAddr: string, overrides?: CallOverrides): Promise<number>;

  getAppManifest(
    app: string,
    overrides?: CallOverrides
  ): Promise<
    [boolean, boolean, BigNumber] & {
      isSuperApp: boolean;
      isJailed: boolean;
      noopMask: BigNumber;
    }
  >;

  isAppJailed(app: string, overrides?: CallOverrides): Promise<boolean>;

  allowCompositeApp(
    targetApp: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isCompositeAppAllowed(
    app: string,
    targetApp: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callAppBeforeCallback(
    app: string,
    callData: BytesLike,
    isTermination: boolean,
    ctx: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callAppAfterCallback(
    app: string,
    callData: BytesLike,
    isTermination: boolean,
    ctx: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  appCallbackPush(
    ctx: BytesLike,
    app: string,
    appAllowanceGranted: BigNumberish,
    appAllowanceUsed: BigNumberish,
    appAllowanceToken: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  appCallbackPop(
    ctx: BytesLike,
    appAllowanceUsedDelta: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  ctxUseAllowance(
    ctx: BytesLike,
    appAllowanceWantedMore: BigNumberish,
    appAllowanceUsedDelta: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  jailApp(
    ctx: BytesLike,
    app: string,
    reason: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callAgreement(
    agreementClass: string,
    callData: BytesLike,
    userData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callAppAction(
    app: string,
    callData: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callAgreementWithContext(
    agreementClass: string,
    callData: BytesLike,
    userData: BytesLike,
    ctx: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callAppActionWithContext(
    app: string,
    callData: BytesLike,
    ctx: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  decodeCtx(
    ctx: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [
      number,
      number,
      BigNumber,
      string,
      string,
      string,
      BigNumber,
      BigNumber,
      BigNumber,
      string,
      string
    ] & {
      appLevel: number;
      callType: number;
      timestamp: BigNumber;
      msgSender: string;
      agreementSelector: string;
      userData: string;
      appAllowanceGranted: BigNumber;
      appAllowanceWanted: BigNumber;
      appAllowanceUsed: BigNumber;
      appAddress: string;
      appAllowanceToken: string;
    }
  >;

  isCtxValid(ctx: BytesLike, overrides?: CallOverrides): Promise<boolean>;

  batchCall(
    operations: {
      operationType: BigNumberish;
      target: string;
      data: BytesLike;
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  forwardBatchCall(
    operations: {
      operationType: BigNumberish;
      target: string;
      data: BytesLike;
    }[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  isTrustedForwarder(
    forwarder: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  versionRecipient(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    APP_WHITE_LISTING_ENABLED(overrides?: CallOverrides): Promise<boolean>;

    CALLBACK_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_APP_LEVEL(overrides?: CallOverrides): Promise<BigNumber>;

    NON_UPGRADABLE_DEPLOYMENT(overrides?: CallOverrides): Promise<boolean>;

    getCodeAddress(overrides?: CallOverrides): Promise<string>;

    initialize(gov: string, overrides?: CallOverrides): Promise<void>;

    proxiableUUID(overrides?: CallOverrides): Promise<string>;

    updateCode(newAddress: string, overrides?: CallOverrides): Promise<void>;

    getGovernance(overrides?: CallOverrides): Promise<string>;

    replaceGovernance(newGov: string, overrides?: CallOverrides): Promise<void>;

    registerAgreementClass(
      agreementClassLogic: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateAgreementClass(
      agreementClassLogic: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isAgreementTypeListed(
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isAgreementClassListed(
      agreementClass: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getAgreementClass(
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    mapAgreementClasses(
      bitmap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string[]>;

    addToAgreementClassesBitmap(
      bitmap: BigNumberish,
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeFromAgreementClassesBitmap(
      bitmap: BigNumberish,
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSuperTokenFactory(overrides?: CallOverrides): Promise<string>;

    getSuperTokenFactoryLogic(overrides?: CallOverrides): Promise<string>;

    updateSuperTokenFactory(
      newFactory: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSuperTokenLogic(
      token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerApp(
      configWord: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    registerAppWithKey(
      configWord: BigNumberish,
      registrationKey: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerAppByFactory(
      app: string,
      configWord: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    isApp(app: string, overrides?: CallOverrides): Promise<boolean>;

    getAppLevel(appAddr: string, overrides?: CallOverrides): Promise<number>;

    getAppManifest(
      app: string,
      overrides?: CallOverrides
    ): Promise<
      [boolean, boolean, BigNumber] & {
        isSuperApp: boolean;
        isJailed: boolean;
        noopMask: BigNumber;
      }
    >;

    isAppJailed(app: string, overrides?: CallOverrides): Promise<boolean>;

    allowCompositeApp(
      targetApp: string,
      overrides?: CallOverrides
    ): Promise<void>;

    isCompositeAppAllowed(
      app: string,
      targetApp: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    callAppBeforeCallback(
      app: string,
      callData: BytesLike,
      isTermination: boolean,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    callAppAfterCallback(
      app: string,
      callData: BytesLike,
      isTermination: boolean,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    appCallbackPush(
      ctx: BytesLike,
      app: string,
      appAllowanceGranted: BigNumberish,
      appAllowanceUsed: BigNumberish,
      appAllowanceToken: string,
      overrides?: CallOverrides
    ): Promise<string>;

    appCallbackPop(
      ctx: BytesLike,
      appAllowanceUsedDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    ctxUseAllowance(
      ctx: BytesLike,
      appAllowanceWantedMore: BigNumberish,
      appAllowanceUsedDelta: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    jailApp(
      ctx: BytesLike,
      app: string,
      reason: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    callAgreement(
      agreementClass: string,
      callData: BytesLike,
      userData: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    callAppAction(
      app: string,
      callData: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    callAgreementWithContext(
      agreementClass: string,
      callData: BytesLike,
      userData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string, string] & { newCtx: string; returnedData: string }>;

    callAppActionWithContext(
      app: string,
      callData: BytesLike,
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    decodeCtx(
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        number,
        number,
        BigNumber,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        string,
        string
      ] & {
        appLevel: number;
        callType: number;
        timestamp: BigNumber;
        msgSender: string;
        agreementSelector: string;
        userData: string;
        appAllowanceGranted: BigNumber;
        appAllowanceWanted: BigNumber;
        appAllowanceUsed: BigNumber;
        appAddress: string;
        appAllowanceToken: string;
      }
    >;

    isCtxValid(ctx: BytesLike, overrides?: CallOverrides): Promise<boolean>;

    batchCall(
      operations: {
        operationType: BigNumberish;
        target: string;
        data: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    forwardBatchCall(
      operations: {
        operationType: BigNumberish;
        target: string;
        data: BytesLike;
      }[],
      overrides?: CallOverrides
    ): Promise<void>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    versionRecipient(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    "AgreementClassRegistered(bytes32,address)"(
      agreementType?: null,
      code?: null
    ): TypedEventFilter<
      [string, string],
      { agreementType: string; code: string }
    >;

    AgreementClassRegistered(
      agreementType?: null,
      code?: null
    ): TypedEventFilter<
      [string, string],
      { agreementType: string; code: string }
    >;

    "AgreementClassUpdated(bytes32,address)"(
      agreementType?: null,
      code?: null
    ): TypedEventFilter<
      [string, string],
      { agreementType: string; code: string }
    >;

    AgreementClassUpdated(
      agreementType?: null,
      code?: null
    ): TypedEventFilter<
      [string, string],
      { agreementType: string; code: string }
    >;

    "AppRegistered(address)"(
      app?: string | null
    ): TypedEventFilter<[string], { app: string }>;

    AppRegistered(
      app?: string | null
    ): TypedEventFilter<[string], { app: string }>;

    "CodeUpdated(bytes32,address)"(
      uuid?: null,
      codeAddress?: null
    ): TypedEventFilter<
      [string, string],
      { uuid: string; codeAddress: string }
    >;

    CodeUpdated(
      uuid?: null,
      codeAddress?: null
    ): TypedEventFilter<
      [string, string],
      { uuid: string; codeAddress: string }
    >;

    "GovernanceReplaced(address,address)"(
      oldGov?: null,
      newGov?: null
    ): TypedEventFilter<[string, string], { oldGov: string; newGov: string }>;

    GovernanceReplaced(
      oldGov?: null,
      newGov?: null
    ): TypedEventFilter<[string, string], { oldGov: string; newGov: string }>;

    "Jail(address,uint256)"(
      app?: string | null,
      reason?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { app: string; reason: BigNumber }
    >;

    Jail(
      app?: string | null,
      reason?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { app: string; reason: BigNumber }
    >;

    "SuperTokenFactoryUpdated(address)"(
      newFactory?: null
    ): TypedEventFilter<[string], { newFactory: string }>;

    SuperTokenFactoryUpdated(
      newFactory?: null
    ): TypedEventFilter<[string], { newFactory: string }>;

    "SuperTokenLogicUpdated(address,address)"(
      token?: string | null,
      code?: null
    ): TypedEventFilter<[string, string], { token: string; code: string }>;

    SuperTokenLogicUpdated(
      token?: string | null,
      code?: null
    ): TypedEventFilter<[string, string], { token: string; code: string }>;
  };

  estimateGas: {
    APP_WHITE_LISTING_ENABLED(overrides?: CallOverrides): Promise<BigNumber>;

    CALLBACK_GAS_LIMIT(overrides?: CallOverrides): Promise<BigNumber>;

    MAX_APP_LEVEL(overrides?: CallOverrides): Promise<BigNumber>;

    NON_UPGRADABLE_DEPLOYMENT(overrides?: CallOverrides): Promise<BigNumber>;

    getCodeAddress(overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    proxiableUUID(overrides?: CallOverrides): Promise<BigNumber>;

    updateCode(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getGovernance(overrides?: CallOverrides): Promise<BigNumber>;

    replaceGovernance(
      newGov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerAgreementClass(
      agreementClassLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateAgreementClass(
      agreementClassLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isAgreementTypeListed(
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isAgreementClassListed(
      agreementClass: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAgreementClass(
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mapAgreementClasses(
      bitmap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    addToAgreementClassesBitmap(
      bitmap: BigNumberish,
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    removeFromAgreementClassesBitmap(
      bitmap: BigNumberish,
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSuperTokenFactory(overrides?: CallOverrides): Promise<BigNumber>;

    getSuperTokenFactoryLogic(overrides?: CallOverrides): Promise<BigNumber>;

    updateSuperTokenFactory(
      newFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateSuperTokenLogic(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerApp(
      configWord: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerAppWithKey(
      configWord: BigNumberish,
      registrationKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerAppByFactory(
      app: string,
      configWord: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isApp(app: string, overrides?: CallOverrides): Promise<BigNumber>;

    getAppLevel(appAddr: string, overrides?: CallOverrides): Promise<BigNumber>;

    getAppManifest(app: string, overrides?: CallOverrides): Promise<BigNumber>;

    isAppJailed(app: string, overrides?: CallOverrides): Promise<BigNumber>;

    allowCompositeApp(
      targetApp: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isCompositeAppAllowed(
      app: string,
      targetApp: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    callAppBeforeCallback(
      app: string,
      callData: BytesLike,
      isTermination: boolean,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    callAppAfterCallback(
      app: string,
      callData: BytesLike,
      isTermination: boolean,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    appCallbackPush(
      ctx: BytesLike,
      app: string,
      appAllowanceGranted: BigNumberish,
      appAllowanceUsed: BigNumberish,
      appAllowanceToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    appCallbackPop(
      ctx: BytesLike,
      appAllowanceUsedDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    ctxUseAllowance(
      ctx: BytesLike,
      appAllowanceWantedMore: BigNumberish,
      appAllowanceUsedDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    jailApp(
      ctx: BytesLike,
      app: string,
      reason: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    callAgreement(
      agreementClass: string,
      callData: BytesLike,
      userData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    callAppAction(
      app: string,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    callAgreementWithContext(
      agreementClass: string,
      callData: BytesLike,
      userData: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    callAppActionWithContext(
      app: string,
      callData: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    decodeCtx(ctx: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    isCtxValid(ctx: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    batchCall(
      operations: {
        operationType: BigNumberish;
        target: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    forwardBatchCall(
      operations: {
        operationType: BigNumberish;
        target: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    versionRecipient(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    APP_WHITE_LISTING_ENABLED(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    CALLBACK_GAS_LIMIT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    MAX_APP_LEVEL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    NON_UPGRADABLE_DEPLOYMENT(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCodeAddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    initialize(
      gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    proxiableUUID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    updateCode(
      newAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getGovernance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    replaceGovernance(
      newGov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerAgreementClass(
      agreementClassLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateAgreementClass(
      agreementClassLogic: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isAgreementTypeListed(
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAgreementClassListed(
      agreementClass: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAgreementClass(
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    mapAgreementClasses(
      bitmap: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addToAgreementClassesBitmap(
      bitmap: BigNumberish,
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    removeFromAgreementClassesBitmap(
      bitmap: BigNumberish,
      agreementType: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSuperTokenFactory(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSuperTokenFactoryLogic(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateSuperTokenFactory(
      newFactory: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateSuperTokenLogic(
      token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerApp(
      configWord: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerAppWithKey(
      configWord: BigNumberish,
      registrationKey: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerAppByFactory(
      app: string,
      configWord: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isApp(
      app: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAppLevel(
      appAddr: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAppManifest(
      app: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isAppJailed(
      app: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    allowCompositeApp(
      targetApp: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isCompositeAppAllowed(
      app: string,
      targetApp: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    callAppBeforeCallback(
      app: string,
      callData: BytesLike,
      isTermination: boolean,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    callAppAfterCallback(
      app: string,
      callData: BytesLike,
      isTermination: boolean,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    appCallbackPush(
      ctx: BytesLike,
      app: string,
      appAllowanceGranted: BigNumberish,
      appAllowanceUsed: BigNumberish,
      appAllowanceToken: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    appCallbackPop(
      ctx: BytesLike,
      appAllowanceUsedDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    ctxUseAllowance(
      ctx: BytesLike,
      appAllowanceWantedMore: BigNumberish,
      appAllowanceUsedDelta: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    jailApp(
      ctx: BytesLike,
      app: string,
      reason: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    callAgreement(
      agreementClass: string,
      callData: BytesLike,
      userData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    callAppAction(
      app: string,
      callData: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    callAgreementWithContext(
      agreementClass: string,
      callData: BytesLike,
      userData: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    callAppActionWithContext(
      app: string,
      callData: BytesLike,
      ctx: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    decodeCtx(
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isCtxValid(
      ctx: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batchCall(
      operations: {
        operationType: BigNumberish;
        target: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    forwardBatchCall(
      operations: {
        operationType: BigNumberish;
        target: string;
        data: BytesLike;
      }[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    isTrustedForwarder(
      forwarder: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    versionRecipient(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
