[profile.default]
src = 'src'
out = 'out/default'
cache_path = 'out/default.cache'
libs = ['../../lib']
solc_version = '0.8.35'
evm_version = 'cancun'
deny_warnings = true
ignored_warnings_from = ["../../lib/openzeppelin-contracts/"]
optimizer = true
optimizer_runs = 200
via_ir = false
remappings = [
    '@superfluid-finance/solidity-semantic-money/src/=src/',
    '@openzeppelin/=../../lib/openzeppelin-contracts/',
    'ds-test/=../../lib/forge-std/lib/ds-test/src/',
    'forge-std/=../../lib/forge-std/src/']

[profile.test]
deny_warnings = false
test = 'test'
out = 'out/test'
cache_path = 'out/test.cache'
via_ir = true # though this is so slow!

[profile.test.fuzz]
runs = 1000

[lint]
lint_on_build = false
ignore = ["test/**"]
