/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as apps from "./apps";
export type { apps };
import type * as interfaces from "./interfaces";
export type { interfaces };
