/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "./common";

export type FrameworkStruct = {
  superfluid: string;
  superTokenFactory: string;
  agreementCFAv1: string;
  agreementIDAv1: string;
};

export type FrameworkStructOutput = [string, string, string, string] & {
  superfluid: string;
  superTokenFactory: string;
  agreementCFAv1: string;
  agreementIDAv1: string;
};

export interface SuperfluidLoaderInterface extends ethers.utils.Interface {
  functions: {
    "loadFramework(string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "loadFramework",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "loadFramework",
    data: BytesLike
  ): Result;

  events: {};
}

export interface SuperfluidLoader extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SuperfluidLoaderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    loadFramework(
      releaseVersion: string,
      overrides?: CallOverrides
    ): Promise<[FrameworkStructOutput] & { result: FrameworkStructOutput }>;
  };

  loadFramework(
    releaseVersion: string,
    overrides?: CallOverrides
  ): Promise<FrameworkStructOutput>;

  callStatic: {
    loadFramework(
      releaseVersion: string,
      overrides?: CallOverrides
    ): Promise<FrameworkStructOutput>;
  };

  filters: {};

  estimateGas: {
    loadFramework(
      releaseVersion: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    loadFramework(
      releaseVersion: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
