require("./contracts/superfluid/Superfluid.test.js");
require("./contracts/superfluid/SuperfluidToken.test.js");
require("./contracts/superfluid/SuperTokenFactory.test.js");
require("./contracts/superfluid/SuperToken.test.js");
require("./contracts/agreements/ConstantFlowAgreementV1.test.js");
require("./contracts/agreements/InstantDistributionAgreementV1.test.js");
require("./contracts/tokens/SETH.test.js");
require("./contracts/ux/SuperUpgrader.test.js");
require("./contracts/misc.test.js");
