[default]
out = 'out'
libs = ['lib']
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@superfluid-finance/=node_modules/@superfluid-finance',
    '@openzeppelin/=node_modules/@openzeppelin']
gas_reports = ["SimpleACLCloseResolver"]

# See more config options https://github.com/gakonst/foundry/tree/master/config