[default]
root = '../../examples/simple-acl-close'
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["SimpleACLCloseResolver"]

# See more config options https://github.com/gakonst/foundry/tree/master/config