[profile.default]
src = 'contracts'
test = 'test'
libs = ['lib']
solc_version = "0.8.35"
evm_version = 'cancun'
optimizer = true
optimizer_runs = 200
remappings = [
    '@superfluid-finance/solidity-semantic-money/src/=lib/solidity-semantic-money/src/',
    '@superfluid-finance/ethereum-contracts/contracts/=lib/ethereum-contracts/contracts/',
    '@superfluid-finance/ethereum-contracts/test/=lib/ethereum-contracts/test/',
    '@openzeppelin-v5/=lib/openzeppelin-contracts/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/']
out = 'out/default'

[profile.ci]
offline = true

[profile.ci.fuzz]
runs = 1000
