/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
    SuperfluidLoader,
    SuperfluidLoaderInterface,
} from "../SuperfluidLoader";

const _abi = [
    {
        inputs: [
            {
                internalType: "contract IResolver",
                name: "resolver",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "constructor",
    },
    {
        inputs: [
            {
                internalType: "string",
                name: "releaseVersion",
                type: "string",
            },
        ],
        name: "loadFramework",
        outputs: [
            {
                components: [
                    {
                        internalType: "contract ISuperfluid",
                        name: "superfluid",
                        type: "address",
                    },
                    {
                        internalType: "contract ISuperTokenFactory",
                        name: "superTokenFactory",
                        type: "address",
                    },
                    {
                        internalType: "contract ISuperAgreement",
                        name: "agreementCFAv1",
                        type: "address",
                    },
                    {
                        internalType: "contract ISuperAgreement",
                        name: "agreementIDAv1",
                        type: "address",
                    },
                ],
                internalType: "struct SuperfluidLoader.Framework",
                name: "result",
                type: "tuple",
            },
        ],
        stateMutability: "view",
        type: "function",
    },
];

export class SuperfluidLoader__factory {
    static readonly abi = _abi;
    static createInterface(): SuperfluidLoaderInterface {
        return new utils.Interface(_abi) as SuperfluidLoaderInterface;
    }
    static connect(
        address: string,
        signerOrProvider: Signer | Provider
    ): SuperfluidLoader {
        return new Contract(
            address,
            _abi,
            signerOrProvider
        ) as SuperfluidLoader;
    }
}
