#!/usr/bin/env bash

maybe_run() {
    exec=$1
    shift
    if which "$exec" &>/dev/null; then
        "$@"
    else
        echo "⚠️  Please install $exec!"
    fi
}

# always lint these
npm run lint:syncpack
maybe_run shellcheck npm run lint:shellcheck
maybe_run actionlint npm run lint:actionlint

# only lint the workspace if there is staged files
for i in $(jq -r '.workspaces.packages | .[]' package.json); do
    if [ -n "$(git diff --name-only HEAD -- "$i")" ]; then (
        echo "= Linting workspace $i"
        cd "$i" || exit 3
        npm run lint
    ) else {
        echo "= Skipping workspace $i: no changed files."
    } fi
done
