#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# always lint these
npm run lint:shellcheck
npm run lint:actionlint

# only lint the workspace if there is staged files
for i in $(jq -r '.workspaces.packages | .[]' package.json); do
    if [ -n "$(git diff --name-only HEAD -- "$i")" ]; then (
        echo "= Linting workspace $i"
        cd "$i" || exit 3
        npm run lint
    ) else {
        echo "= Skipping workspace $i: no changed files."
    } fi
done
