name: Reusable Workflow | Automation Contracts

on:
  workflow_call:

jobs:
  test-automation-contract:
    name: Test Automation Contracts

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare devShell
        run: |
          echo 'nix develop -c bash $@' > devShell.sh
          yarn install --frozen-lockfile

      - name: Lint and build
        run: |
          yarn lint
          yarn build
        shell: sh devShell.sh {0}

      - name: Test automation-contracts-scheduler
        run: |
          yarn workspace scheduler test
        shell: sh devShell.sh {0}

      - name: Test automation-contracts-autowrap
        run: |
          yarn workspace autowrap test
        shell: sh devShell.sh {0}

