name: Reusable Workflow | Run Unit and Integration Tests on Local Subgraph

on:
  workflow_call:

env:
  DEV_SHELL_NAME: ci-node22
  ethereum-contracts-working-directory: ./packages/ethereum-contracts
  sdk-core-working-directory: ./packages/sdk-core
  subgraph-working-directory: ./packages/subgraph

jobs:
  subgraph-unit-tests:
    name: Run subgraph unit tests
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: nix develop .#${{ env.DEV_SHELL_NAME }} -c bash -xe {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup workflow base
        id: base
        uses: ./.github/actions/setup-workflow-base
        with:
          package-name: subgraph
          cache-key-prefix: subgraph-${{ env.DEV_SHELL_NAME }}-unit-tests-
          dev-shell-name: ${{ env.DEV_SHELL_NAME }}

      - name: Install dependencies
        if: steps.base.outputs.cache-hit != 'true'
        run: |
          yarn install --immutable
          npx tsc --version
          npx graph --version

      - name: Build ethereum contracts
        if: steps.base.outputs.cache-hit != 'true'
        run: |
          yarn lint
          yarn build
        working-directory: ${{ env.ethereum-contracts-working-directory }}

      - name: Run unit tests
        if: steps.base.outputs.cache-hit != 'true'
        run: yarn matchstick
        working-directory: ${{ env.subgraph-working-directory }}

  subgraph-integration-tests:
    name: Run subgraph integration tests

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: nix develop .#${{ env.DEV_SHELL_NAME }} -c bash -xe {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup workflow base
        id: base
        uses: ./.github/actions/setup-workflow-base
        with:
          package-name: subgraph
          cache-key-prefix: subgraph-${{ env.DEV_SHELL_NAME }}-integration-tests-
          dev-shell-name: ${{ env.DEV_SHELL_NAME }}

      - name: Install dependencies
        if: steps.base.outputs.cache-hit != 'true'
        run: yarn install --immutable

      - name: Build contracts
        if: steps.base.outputs.cache-hit != 'true'
        run: yarn build
        working-directory: ${{ env.ethereum-contracts-working-directory }}

      - name: Build SDK core
        if: steps.base.outputs.cache-hit != 'true'
        # build sdk-core because subgraph tests use sdk-core
        run: yarn build
        working-directory: ${{ env.sdk-core-working-directory }}

      - name: Start hardhat node
        if: steps.base.outputs.cache-hit != 'true'
        run: ./tasks/startHardhatNode.sh start
        working-directory: ${{ env.sdk-core-working-directory }}

      - name: Prepare files for local testing
        if: steps.base.outputs.cache-hit != 'true'
        run: yarn prepare-local
        working-directory: ${{ env.subgraph-working-directory }}

      - name: Setup graph node
        if: steps.base.outputs.cache-hit != 'true'
        run: |
          ./tasks/setup-graph-node.sh
        working-directory: ${{ env.subgraph-working-directory }}

      - name: Run subgraph integration test suite
        if: steps.base.outputs.cache-hit != 'true'
        run: yarn test --network localhost
        working-directory: ${{ env.subgraph-working-directory }}
