name: Reusable Workflow | Automation Contracts

on:
  workflow_call:

jobs:
  test-automation-contract:
    name: Test Automation Contracts

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    defaults:
      run:
        shell: nix develop .#ci-node${{ matrix.node-version }} -c bash -xe {0}

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install, lint and build
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn build

      - name: Test automation-contracts-scheduler
        run: |
          echo "FOUNDRY_PROFILE=ci" >> $GITHUB_ENV
          echo "FOUNDRY_SOLC_VERSION=$SOLC" >> $GITHUB_ENV
          yarn workspace scheduler test

      - name: Test automation-contracts-autowrap
        run: |
          echo "FOUNDRY_PROFILE=ci" >> $GITHUB_ENV
          echo "FOUNDRY_SOLC_VERSION=$SOLC" >> $GITHUB_ENV
          yarn workspace autowrap test
