name: Reusable Workflow | Test Hardhat-Deployer

on:
  workflow_call:

jobs:
  test-hardhat-deployer:
    name: Test Hardhat-Deployer

    runs-on: ubuntu-latest

    env:
      contracts-working-directory: ./packages/ethereum-contracts
      hardhat-working-directory: ./packages/hardhat-deployer

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: "Install contract dependencies"
        run: yarn install --frozen-lockfile
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Build contracts"
        run: yarn build:contracts
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Install dependencies"
        run: yarn
        working-directory: ${{ env.hardhat-working-directory }}

      - name: "Run test suite"
        run: yarn test
        working-directory: ${{ env.hardhat-working-directory }}