name: Reusable Workflow | Test Hardhat-Deployer

on:
  workflow_call:

jobs:
  test-hardhat-deployer:
    name: Test Hardhat-Deployer

    runs-on: ubuntu-latest

    env:
      contracts-working-directory: ./packages/ethereum-contracts

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: "Install contract dependencies"
        run: yarn install
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Build contracts"
        run: yarn build:contracts
        working-directory: ${{ env.contracts-working-directory }}
      
      - name: "Install local hardhat instance"
        run: |
          yarn init -y
          yarn add hardhat
        working-directory: ./packages/hardhat-deployer/test/fixture-projects/hardhat-project

      - name: "Run test suite"
        run: yarn test
        working-directory: ./packages/hardhat-deployer
