name: Reusable Workflow | Run Unit and Integration Tests on Local Subgraph

on:
  workflow_call:

jobs:
  subgraph-unit-tests:
    name: Run subgraph unit tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"

      - name: "Install dependencies"
        run: yarn install --frozen-lockfile

      - name: "Build contracts"
        run: yarn build
        working-directory: ./packages/ethereum-contracts

      - name: "Run unit tests"
        run: yarn matchstick
        working-directory: ./packages/subgraph

  subgraph-end-to-end-integration:
    name: Run subgraph integration tests

    runs-on: ubuntu-latest

    env:
      subgraph-working-directory: ./packages/subgraph
      sdk-core-working-directory: ./packages/sdk-core

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"

      - name: "Install dependencies"
        run: yarn install --frozen-lockfile

      - name: "Build contracts"
        run: yarn build
        working-directory: ./packages/ethereum-contracts

      - name: "Start hardhat node"
        run: |
          ./tasks/startHardhatNode.sh start
        working-directory: ${{ env.sdk-core-working-directory }}

      - name: "Build SDK-Core"
        # build sdk-core because of auto linking to dependency
        run: yarn build
        working-directory: ${{ env.sdk-core-working-directory }}

      - name: "Deploy Framework and Tokens"
        run: npx hardhat run dev-scripts/run-deploy-contracts-and-token.js --network localhost
        working-directory: ./packages/ethereum-contracts

      - name: "Prepare files for local testing"
        run: yarn prepare-local
        working-directory: ${{ env.subgraph-working-directory }}

      - name: "Run setup-graph-node"
        run: |
          chmod +x ./tasks/setup-graph-node.sh
          ./tasks/setup-graph-node.sh
        working-directory: ${{ env.subgraph-working-directory }}

      - name: "Docker compose"
        run: docker-compose up &
        working-directory: ${{ env.subgraph-working-directory }}

      - name: "Run subgraph integration test suite"
        run: yarn test
        working-directory: ${{ env.subgraph-working-directory }}