name: Reusable Workflow | Automation Contracts

on:
  workflow_call:

jobs:
  test-automation-contract:
    name: Test Automation Contracts

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]

    defaults:
      run:
        shell: nix develop -c bash {0}

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install, lint and build
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn build

      - name: Test automation-contracts-scheduler
        run: |
          yarn workspace scheduler test

      - name: Test automation-contracts-autowrap
        run: |
          yarn workspace autowrap test

