name: Reusable Workflow | Test HotFuzz

on:
  workflow_call:

jobs:
  test-spec-haskell:
    name: Test HotFuzz - Linux

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v19
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: cache
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-${{ github.sha }}
          path: ~/.cabal/store
          restore-keys: ${{ runner.os }}-

      - name: Create devShell
        run: |
          echo 'nix develop .#ci-hot-fuzz -c bash $@' > devShell.sh

      - name: Run tests
        run: |
          cd packages/hot-fuzz
          ./hotfuz contracts/superfluid-tests/SuperHotFuzz.sol
        shell: sh devShell.sh {0}
        env:
          ECHIDNA_TEST: echidna-test --test-limit 10
