name: CD | Create ethereum-contracts Stable Release Draft
env:
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    branches:
      - "release-ethereum-contracts-stable"
    paths:
      - "packages/ethereum-contracts/**"
      - ".github/workflows/cd.ethereum-contracts-stable.create-release-drafts.yml"

jobs:

  create-release-draft:
    name: Create Release Draft

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Check package versions
        id: check_versions
        run: |
          # ethereum-contracts
          PUBLISHED_ETHEREUM_CONTRACTS_VERSION=`npm show @superfluid-finance/ethereum-contracts@latest version`
          NEW_ETHEREUM_CONTRACTS_VERSION=`jq -r .version packages/ethereum-contracts/package.json`
          if [ "$PUBLISHED_ETHEREUM_CONTRACTS_VERSION" != "$NEW_ETHEREUM_CONTRACTS_VERSION" ];then
            echo "PUBLISH_ETHEREUM_CONTRACTS=1" >> $GITHUB_ENV
            echo "ethereum-contracts changed: $PUBLISHED_ETHEREUM_CONTRACTS_VERSION -> $NEW_ETHEREUM_CONTRACTS_VERSION"
          else
            echo ethereum-contracts unchanged: $PUBLISHED_ETHEREUM_CONTRACTS_VERSION
          fi

          echo "::set-output name=NEW_ETHEREUM_CONTRACTS_VERSION::$NEW_ETHEREUM_CONTRACTS_VERSION"

      - name: Create ethereum-contracts release draft
        if: env.PUBLISH_ETHEREUM_CONTRACTS == 1
        id: create_release_ethereum_contracts
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ethereum-contracts@v${{ steps.check_versions.outputs.NEW_ETHEREUM_CONTRACTS_VERSION }}
          release_name: ethereum-contracts@v${{ steps.check_versions.outputs.NEW_ETHEREUM_CONTRACTS_VERSION }}
          body: |
            Changes in this ethereum-contracts stable release
            ## Changed
            ## Added
            ## Fixes
            ## Breaking
          draft: true
