name: CD | Create Subgraph Stable Release Draft

on:
  workflow_dispatch:
  push:
    branches:
      - "release-subgraph-v1"
    paths:
      - "packages/subgraph/**"
      - ".github/workflows/cd.subgraph-stable.create-release-drafts.yml"

jobs:

  create-release-draft:
    name: Create Release Draft

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org/

      - name: Check package versions
        id: check_versions
        run: |
          # subgraph
          NEW_SUBGRAPH_VERSION=`jq -r .version packages/subgraph/package.json`
          if git tag | grep -e "^subgraph" | grep v$NEW_SUBGRAPH_VERSION;then
            echo subgraph version exists
          else
            echo "PUBLISHED_SUBGRAPH_VERSION=1" >> $GITHUB_ENV
            echo "subgraph changed: $NEW_SUBGRAPH_VERSION"
          fi

          echo "::set-output name=NEW_SUBGRAPH_VERSION::$NEW_SUBGRAPH_VERSION"

      - name: Create subgraph stable release draft
        if: env.PUBLISHED_SUBGRAPH_VERSION == 1
        id: create_release_SUBGRAPH
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: subgraph@v${{ steps.check_versions.outputs.NEW_SUBGRAPH_VERSION }}
          release_name: subgraph@v${{ steps.check_versions.outputs.NEW_SUBGRAPH_VERSION }}
          body: |
            Changes in this subgraph stable release
            ## Changed
            ## Added
            ## Fixes
            ## Breaking
          draft: true
