name: CD | Create SDK-Core Stable Release Draft
env:
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

on:
  workflow_dispatch:
  push:
    branches:
      - "release-sdk-core-stable"
    paths:
      - "packages/sdk-core/**"
      - ".github/workflows/cd.sdk-core-stable.create-release-drafts.yml"

jobs:

  test-sdk-core-query-schema-against-deployed-v1-subgraphs:
    uses: ./.github/workflows/call.check-query-schema-against-subgraph.yml
    name: Test SDK-Core Query Schema and Queries Against Deployed V1 Subgraphs
    with:
      subgraph-release: v1

  test-sdk-core-with-v1-release-subgraph:
    uses: ./.github/workflows/call.test-sdk-core.yml
    name: Build and Test SDK-Core (Release branch)
    with:
      subgraph-release: v1
      subgraph-endpoint: ''
      run-coverage-tests: false

  create-release-draft:
    name: Create Release Draft

    runs-on: ubuntu-latest

    needs: [ test-sdk-core-query-schema-against-deployed-v1-subgraphs
           , test-sdk-core-with-v1-release-subgraph
           ]
    
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: https://registry.npmjs.org/

      - name: Check package versions
        id: check_versions
        run: ./tasks/check-package-version.sh sdk-core

      - name: Create sdk-core stable release draft
        if: env.sdk-core == 1
        id: create_release_sdk_core
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: sdk-core@v${{ steps.check_versions.outputs.sdk-core }}
          release_name: sdk-core@v${{ steps.check_versions.outputs.sdk-core }}
          body: |
            Changes in this sdk-core stable release
            ## Changed
            ## Added
            ## Fixes
            ## Breaking
          draft: true
