name: CI Test Subgraph Locally

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: 'Test branch (feature/dev/v1 ...)'
        required: true
        default: 'feature'

jobs:
  test-subgraph:
    name: Build and test subgraph (Feature Branch)

    runs-on: ubuntu-latest
    
    env:
      subgraph-working-directory: ./packages/subgraph
      contracts-working-directory: ./packages/ethereum-contracts
      sdk-working-directory: ./packages/js-sdk

    steps:
      - uses: actions/checkout@v2

      - name: "Checkout graph node repo and set up local graph node"
        uses: actions/checkout@v2
        with:
          repository: graphprotocol/graph-node
          path: graph-node
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Run setup because linux and docker-compose"
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          chmod +x setup.sh
          ./setup.sh
        working-directory: ./graph-node/docker
      
      - name: "Docker compose"
        run: docker-compose up &
        working-directory: ./graph-node/docker

      - name: "Run ganache-cli node"
        run: ganache-cli -h 0.0.0.0 -m "test test test test test test test test test test test junk" &
        working-directory: ${{ env.subgraph-working-directory }}

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      
      - name: "Install yarn"
        run: npm install -g yarn ganache-cli

      - name: "Install contract dependencies"
        run: yarn install
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Build contracts"
        run: yarn run build:contracts
        working-directory: ${{ env.contracts-working-directory }}

      - name: "Install subgraph dependencies"
        run: yarn install
        working-directory: ${{ env.subgraph-working-directory }}

      - name: "Get ABI for subgraph.yaml"
        run: node scripts/getAbi.js
        working-directory: ${{ env.subgraph-working-directory }}

      - name: "Get abi.js file for js-sdk to deploy locally"
        run: |
          chmod +x ./tasks/build-abi-js.sh
          ./tasks/build-abi-js.sh
        working-directory: ${{ env.sdk-working-directory }}

      - name: "Deploy contracts and token locally"
        run: npx hardhat run scripts/deployContractsAndToken.ts --network localhost
        working-directory: ${{ env.subgraph-working-directory }}


      - name: "Prepare, build and deploy subgraph locally"
        run: yarn prepare-local && yarn codegen && yarn create-local && yarn deploy-local
        working-directory: ${{ env.subgraph-working-directory }}

      - name: "Run integration test suite"
        run: npx hardhat test --network localhost
        working-directory: ${{ env.subgraph-working-directory }}
