name: CI Master

on:
  push:
    branches: ["master"]
    paths:
      - 'packages/**'
      - '.github/workflows/ci.master.yml'

jobs:

  build:
    name: Build and test essential packages of master branch

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Show contexts
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.sha: ${{ github.sha }}
          echo github.repository: ${{ github.repository }}
          echo github.ref: ${{ github.ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install, lint, build, and test
        run: |
          yarn install --frozen-lockfile
          yarn lint
          yarn build
          yarn test
