name: Create PR Artifact

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]

jobs:
  create_pr_artifact:
    name: Create PR Artifact

    runs-on: ubuntu-latest

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Show context
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.event.number: ${{ github.event.number }}
          echo github.sha: ${{ github.sha }}
          echo github.repository: ${{ github.repository }}
          echo github.ref: ${{ github.ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}
          echo "github.event.pull_request"
          echo "  .number" ${{ github.event.pull_request.number }}
          echo "  .state" ${{ github.event.pull_request.state }}
          echo "  .locked" ${{ github.event.pull_request.locked }}
          echo "  .draft" ${{ github.event.pull_request.draft }}

      - name: Check changeset
        run: tasks/check-changeset.sh ${{ github.sha }} dev

      - name: Install dependencies
        if: env.PUBLISH_PR_ARTIFACT == 1
        run: yarn install --frozen-lockfile

      - name: Build
        if: env.PUBLISH_PR_ARTIFACT == 1
        run: yarn build

      - name: Setup PR package versions locally
        if: env.PUBLISH_PR_ARTIFACT == 1
        run: |
          prNumber=${{ github.event.number }}
          shortRev=$(git rev-parse --short ${{ github.sha }})
          preId=PR${prNumber}.${shortRev}
          yarn lerna version prerelease --yes --no-git-tag-version --preid ${preId}

      - name: Create packages
        if: env.PUBLISH_PR_ARTIFACT == 1
        run: |
          prNumber=${{ github.event.number }}
          dirName="bin/${prNumber}"
          mkdir -p $dirName
          for d in packages/*/ ; do (
            cd "$d"
            tgz=$(npm pack)
            cp $tgz "../../$dirName/"
          ) done
          cd $dirName
          sha="${{ github.event.pull_request.head.sha }}"
          for f in * ; do
            mv -- "$f" "${f%.tgz}-${sha:0:7}.tgz"
          done

      - name: Create empty artifact
        if: env.PUBLISH_PR_ARTIFACT != 1
        run: |
          prNumber=${{ github.event.number }}
          dirName="bin/${prNumber}"
          mkdir -p $dirName
          touch $dirName/.empty

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr-packages
          path: bin
          retention-days: 1
