name: Daily protocol-monorepo slack message

on:
  workflow_dispatch:
  schedule:
    - cron: 0 11 * * 1-5

jobs:
  send-slack-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
        

      - name: Send slack message
        working-directory: tasks
        run: |
          npm install ethers --force
          node daily-slack-bot.js
        env: 
          CI_SLACK_WEBHOOK: ${{ secrets.CI_SLACK_WEBHOOK }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
          POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
          SNOWTRACE_API_KEY: ${{ secrets.SNOWTRACE_API_KEY }}
          OPTIMISTIC_API_KEY: ${{ secrets.OPTIMISTIC_API_KEY }}
          ARBISCAN_API_KEY: ${{ secrets.ARBISCAN_API_KEY }}
          BSCSCAN_API_KEY: ${{ secrets.BSCSCAN_API_KEY }}
          CELOSCAN_API_KEY: ${{ secrets.CELOSCAN_API_KEY }}
          GNOSISSCAN_API_KEY: ${{ secrets.GNOSISSCAN_API_KEY}}
          ZKEVM_POLYGONSCAN_API_KEY: ${{ secrets.ZKEVM_POLYGONSCAN_API_KEY }}