name: Daily Subgraph and Query Sync Check

on:
  schedule:
    - cron: 0 11 * * *

jobs:
  test-query-schema-against-deployed-v1-subgraphs:
    uses: ./.github/workflows/call.check-query-schema-against-subgraph.yml
    name: "Test Query Schema and Queries Against Local and Deployed V1 Subgraphs"
    with:
      subgraph-release: v1

  test-query-schema-against-deployed-dev-subgraphs:
    uses: ./.github/workflows/call.check-query-schema-against-subgraph.yml
    name: "Test Query Schema and Queries Against Local and Deployed Dev Subgraphs"
    with:
      subgraph-release: dev