# Handler Workflow Summary
# This handler workflow file can be used to deploy to the Satsuma subgraph, 
# it can deploy to all networks or a specific network.
# It will deploy with the specified satsuma_version_label and the specified network, 
# if no network is passed, then it will deploy to all networks.

name: Handler | Deploy Satsuma Subgraph
env:
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

on:
  workflow_dispatch:
    inputs:
      satsuma_version_label:
        required: true
        type: string
        description: 'The version label for Satsuma endpoint (e.g. v0.0.x)'
      network:
        required: true
        type: string
        description: 'The network you want to deploy to (matic, xdai, eth-mainnet, etc.) or `all` for all networks.'
jobs:
  build-and-test-local-subgraph:
    uses: ./.github/workflows/call.test-local-subgraph.yml
    name: Run Subgraph Unit and Integration Tests

  build-and-test-local-subgraph-against-previous-sdk-core-releases:
    uses: ./.github/workflows/call.test-subgraph-on-previous-sdk-core-versions.yml
    name: Test Local Subgraph against SDK-Core previous and current releases
    with:
      subgraph-release: ''
      subgraph-endpoint: http://localhost:8000/subgraphs/name/superfluid-test

  deploy-subgraph:
    uses: ./.github/workflows/call.deploy-satsuma-subgraph.yml
    needs: [ 
            build-and-test-local-subgraph
           , build-and-test-local-subgraph-against-previous-sdk-core-releases
           ]
    name: Deploy Satsuma Subgraph
    with:
      satsuma_version_label: ${{ github.event.inputs.satsuma_version_label }}
      network: ${{ github.event.inputs.network }}
    secrets:
      SATSUMA_DEPLOY_KEY: ${{ secrets.SATSUMA_DEPLOY_KEY }}