name: Deploy to Mainnet

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Protocol release version (test/master/v1/etc.)'
        required: true
        default: 'v1'
      network:
        description: 'Mainnet on which to deploy/upgrade'
        required: true
      environments:
        description: 'Additional env vars, separated by semicolons'
        required: false

jobs:

  deploy-to-mainnet:
    name: Deploy to mainnet

    runs-on: ubuntu-22.04

    env:
      RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      DEFAULT_MNEMONIC: ${{ secrets.BUILD_AGENT_MNEMONIC }}
      PROVIDER_URL_TEMPLATE: ${{ secrets.PROVIDER_URL_TEMPLATE }}

    defaults:
      run:
        shell: nix develop .#ci-default -c bash -xe {0}

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v13

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn build-for-contracts-dev

      - name: Deploy to ${{ github.event.inputs.network }}
        run: |
          cd packages/ethereum-contracts
          echo "${{ github.event.inputs.environments }}" | sed 's/;/\n/' > .env
          ./new-ops-scripts/upgrade-framework.sh ${{ github.event.inputs.network }}
        env:
          GOVERNANCE_ADMIN_TYPE: MULTISIG
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
