name: Destroy Outdated PR Packages
env:
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

on:
  pull_request:
    types: [closed]

jobs:
  destroy_pr_packages:
    name: Destroy PR Packages

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Show context
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.sha: ${{ github.sha }}
          echo github.repository: ${{ github.repository }}
          echo github.ref: ${{ github.ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}

      - name: Get PR data
        id: pr
        run: |
          ls -R pr-packages
          pr_number=$(ls pr-packages)
          n_packages=$(ls pr-packages/$pr_number | wc -l)
          echo pr_number: $pr_number
          echo n_packages: $n_packages
          echo "::set-output name=pr_number::$pr_number"
          echo "::set-output name=n_packages::$n_packages"

      - name: Delete Old @superfluid-finance/js-sdk@PR Package
        uses: actions/delete-package-versions@v2.0.1
        with:
          package-name: '@superfluid-finance/js-sdk@PR${{ steps.pr.outputs.pr_number }}'

      - name: Delete Old @superfluid-finance/ethereum-contracts@PR Package
        uses: actions/delete-package-versions@v2.0.1
        with:
          package-name: '@superfluid-finance/ethereum-contracts@PR${{ steps.pr.outputs.pr_number }}'

      - name: Delete Old @superfluid-finance/sdk-core@PR Package
        uses: actions/delete-package-versions@v2.0.1
        with:
          package-name: '@superfluid-finance/sdk-core@PR${{ steps.pr.outputs.pr_number }}'

      - name: Delete Old @superfluid-finance/sdk-redux@PR Package
        uses: actions/delete-package-versions@v2.0.1
        with:
          package-name: '@superfluid-finance/sdk-redux@PR${{ steps.pr.outputs.pr_number }}'
