name: Publisher & CI

on:
  push:
    branches: ["dev"]
    paths:
      - ".github/workflows/handler.publish-dev-release-packages.yml"
      - ".github/workflows/call.*.yml"
      - "package.json"
      - "yarn.lock"
      - "packages/**"
      - "codecov.yml"
      # - "**.md" are commented out because docs updates should go into the packages
  release:
    types: [published]

jobs:
  check:
    name: Checking what packages need to be built
    if: github.event_name == 'push'

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: nix develop .#ci-minimum -c bash -xe {0}

    outputs:
      build_subgraph: ${{ env.BUILD_SUBGRAPH }}

    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v13

      - name: Show contexts
        env:
          HEAD_REF: ${{ github.head_ref }}
          GITHUB_REF: ${{ github.ref }}
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.sha: ${{ github.sha }}
          echo github.repository: ${{ github.repository }}
          echo github.ref: "$GITHUB_REF"
          echo github.head_ref: "$HEAD_REF"
          echo github.base_ref: ${{ github.base_ref }}

      - name: Run global lint
        run: |
          tasks/shellcheck-all-tasks.sh
          actionlint .github/workflows/*.yml

      - name: Create build set
        run: tasks/create-build-set.sh ${{ github.sha }} dev origin

  test-spec-haskell:
    uses: ./.github/workflows/call.test-spec-haskell.yml
    name: Build and Test Spec Haskell (Canary Branch)
    needs: [check]

  test-solidity-semantic-money:
    name: Build and Test Solidity Semantic Money (Canary Branch)
    uses: ./.github/workflows/call.test-solidity-semantic-money.yml
    needs: [check]

  test-ethereum-contracts:
    name: Test ethereum-contracts (Canary Branch)
    uses: ./.github/workflows/call.test-ethereum-contracts.yml
    needs: [check]
    with:
      run-coverage-tests: false

  coverage-ethereum-contracts:
    name: Coverage test ethereum-contracts (Canary Branch)
    uses: ./.github/workflows/call.test-ethereum-contracts.yml
    needs: [check]
    with:
      run-coverage-tests: true

  test-hot-fuzz:
    uses: ./.github/workflows/call.test-hot-fuzz.yml
    name: Hot Fuzz (Development Branch)
    needs: [check]

  test-sdk-core:
    uses: ./.github/workflows/call.test-sdk-core.yml
    name: Build and Test SDK-Core (Development Branch)
    needs: [check]
    with:
      subgraph-release: local
      subgraph-endpoint: http://localhost:8000/subgraphs/name/superfluid-test
      run-coverage-tests: false

  coverage-sdk-core:
    uses: ./.github/workflows/call.test-sdk-core.yml
    name: Build and Test SDK-Core Coverage (Canary Branch)
    needs: [check]
    with:
      subgraph-release: local
      subgraph-endpoint: http://localhost:8000/subgraphs/name/superfluid-test
      run-coverage-tests: true

  test-subgraph:
    uses: ./.github/workflows/call.test-local-subgraph.yml
    name: Build and Test Subgraph (Development Branch)
    needs: [check]

  test-automation-contracts:
    uses: ./.github/workflows/call.test-automation-contracts.yml
    name: Build and Test Automation Contracts (Canary Branch)
    needs: [check]

  # deploy subgraph if changes are made, we can call this every time, but we won't actually do any deployments
  # if the IPFS hash generated stays the same (no mapping logic changes)
  deploy-subgraph-changes:
    uses: ./.github/workflows/call.deploy-subgraph.yml
    name: "Deploy Hosted Service Subgraph to dev endpoints on all networks"
    needs: [check, test-subgraph]
    if: needs.check.outputs.build_subgraph
    with:
      vendor: graph
      deployment_env: dev
      network: "all"
    secrets:
      THE_GRAPH_ACCESS_TOKEN: ${{ secrets.THE_GRAPH_ACCESS_TOKEN }}

  upload-coverage-reports:
    name: Upload Coverage Reports (Feature Branch)
    uses: ./.github/workflows/call.upload-coverage-reports.yml
    needs: [coverage-ethereum-contracts, coverage-sdk-core]
    secrets: inherit

  all-packages-tested:
    name: All packages tested (Dev Branch)
    runs-on: ubuntu-22.04
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-not-requiring-successful-dependent-jobs
    if: ${{ always() && github.event_name == 'push' }}

    needs: [ test-spec-haskell
           , test-solidity-semantic-money
           , test-ethereum-contracts, coverage-ethereum-contracts
           , test-hot-fuzz
           , test-sdk-core, coverage-sdk-core
           , test-subgraph
           , test-automation-contracts
           ]
    steps:
      - name: Test Results
        run: |
          function check_result() {
            local package_name="$1"
            local result="$2"
            if [ "$result" == "skipped" ];then
              echo "Skipped $package_name package."
            else
              echo "Checking if $package_name package test passes..."
              test "$result" == "success"
              echo "Passed."
            fi
          }
          check_result spec-haskell ${{ needs.test-spec-haskell.result }}
          check_result solidity-semantic-money ${{ needs.test-solidity-semantic-money.result }}
          check_result test-ethereum-contracts ${{ needs.test-ethereum-contracts.result }}
          check_result coverage-ethereum-contracts ${{ needs.coverage-ethereum-contracts.result }}
          check_result hot-fuzz ${{ needs.test-hot-fuzz.result }}
          check_result test-sdk-core ${{ needs.test-sdk-core.result }}
          check_result coverage-sdk-core ${{ needs.coverage-sdk-core.result }}
          check_result subgraph ${{ needs.test-subgraph.result }}
          check_result automation-contracts ${{ needs.test-automation-contracts.result }}

  publish-npm-packages:
    name: Publish canary packages to registries
    # Only run this if we are in a push event (canary flow)
    if: github.event_name == 'push'

    permissions:
      contents: read
      id-token: write
    needs: [all-packages-tested]

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: nix develop .#ci-default -c bash -xe {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 26.x
          registry-url: 'https://registry.npmjs.org'

      - uses: DeterminateSystems/nix-installer-action@v13

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn --cwd packages/sdk-core set-default-subgraph-release-tag
          yarn build
        env:
          SUBGRAPH_RELEASE_TAG: dev

      - name: Setup canary package versions locally
        run: |
          shortRev=$(git rev-parse --short ${{ github.sha }})
          preId=dev.${shortRev}
          yarn lerna version prerelease --yes --no-git-tag-version --preid "${preId}"

      - name: Publish to npm
        shell: bash
        run: |
          tasks/npm-publish.sh packages/ethereum-contracts/ dev --verbose
          tasks/npm-publish.sh packages/sdk-core/ dev --verbose
          tasks/npm-publish.sh packages/sdk-redux/ dev --verbose
          tasks/npm-publish.sh packages/metadata/ dev --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-sdk-html-docs:
    name: Publish canary HTML docs
    # Only run this if we are in a push event
    if: github.event_name == 'push'

    needs: [all-packages-tested]

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: nix develop .#ci-default -c bash -xe {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: superfluid-finance/build-scripts
          path: build-scripts

      - uses: DeterminateSystems/nix-installer-action@v13

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn --cwd packages/sdk-core set-default-subgraph-release-tag
          yarn build
        env:
          SUBGRAPH_RELEASE_TAG: dev

      - name: Build HTML documentation of SDK-s
        run: |
          yarn --cwd packages/sdk-core doc:html
          yarn --cwd packages/sdk-redux doc:html

      - name: Upload sdk-core HTML documentation
        uses: ./build-scripts/s3cloudfront-hosting/actions/sync
        with:
          local_build_dir: packages/sdk-core/dist/docs
          aws_region: eu-west-2
          aws_access_key_id: ${{ secrets.SITE_DEPLOYER_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.SITE_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          s3_uri: ${{ format('{0}sdk-core@dev', secrets.SITE_DEPLOYER_AWS_S3_DOCS_URI) }}
          cloudfront_distribution_id: E3JEO5R14CT8IH

      - name: Upload sdk-redux HTML documentation
        uses: ./build-scripts/s3cloudfront-hosting/actions/sync
        with:
          local_build_dir: packages/sdk-redux/dist/docs
          aws_region: eu-west-2
          aws_access_key_id: ${{ secrets.SITE_DEPLOYER_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.SITE_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          s3_uri: ${{ format('{0}sdk-redux@dev', secrets.SITE_DEPLOYER_AWS_S3_DOCS_URI) }}
          cloudfront_distribution_id: E3JEO5R14CT8IH

  publish-release:
    name: Publish release package
    if: github.event_name == 'release'

    permissions:
      contents: read
      id-token: write

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: nix develop .#ci-default -c bash -xe {0}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: superfluid-finance/build-scripts
          path: build-scripts

      - uses: actions/setup-node@v4
        with:
          node-version: 26.x
          registry-url: 'https://registry.npmjs.org'

      - uses: DeterminateSystems/nix-installer-action@v13

      - name: Parse Tag
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          if echo -n "$GITHUB_REF" | grep -qE "refs/tags/ethereum-contracts@";then
            echo "PUBLISH_ETHEREUM_CONTRACTS=1" >> "$GITHUB_ENV"
          fi
          if echo -n "$GITHUB_REF" | grep -qE "refs/tags/sdk-core@";then
            echo "PUBLISH_SDK_CORE=1" >> "$GITHUB_ENV"
          fi
          if echo -n "$GITHUB_REF" | grep -qE "refs/tags/sdk-redux@";then
            echo "PUBLISH_SDK_REDUX=1" >> "$GITHUB_ENV"
          fi
          if echo -n "$GITHUB_REF" | grep -qE "refs/tags/metadata@";then
            echo "PUBLISH_METADATA=1" >> "$GITHUB_ENV"
          fi

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build ethereum-contracts package
        if: env.PUBLISH_ETHEREUM_CONTRACTS == 1
        run: |
          yarn --cwd packages/ethereum-contracts build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish ethereum-contracts package
        if: env.PUBLISH_ETHEREUM_CONTRACTS == 1
        shell: bash
        run: |
          tasks/npm-publish.sh packages/ethereum-contracts/ latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build sdk-core package
        if: env.PUBLISH_SDK_CORE == 1
        run: |
          yarn --cwd packages/sdk-core get-graphql-schema:v1
          yarn --cwd packages/ethereum-contracts build
          yarn --cwd packages/sdk-core build
          yarn --cwd packages/sdk-core doc:html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish sdk-core package
        id: publish-sdk-core
        if: env.PUBLISH_SDK_CORE == 1
        shell: bash
        run: |
          tasks/npm-publish.sh packages/sdk-core/ latest

          PUBLISHED_VERSION=$(jq -r .version packages/sdk-core/package.json)

          echo "PUBLISHED_VERSION=$PUBLISHED_VERSION" >> "$GITHUB_OUTPUT"

          # Create redirect from root
          mkdir sdk-core-redirect
          printf '<!DOCTYPE html><html><head><title>Redirecting...</title><meta charset="UTF-8"><meta http-equiv="refresh" content="0;URL=%s" /><meta http-equiv="Cache-Control" content="no-store" /></head><body><p>Redirecting to latest documentation...</p></body></html>' "https://refs.superfluid.finance/sdk-core@$PUBLISHED_VERSION" \
          > sdk-core-redirect/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload sdk-core HTML documentation
        if: env.PUBLISH_SDK_CORE == 1
        uses: ./build-scripts/s3cloudfront-hosting/actions/sync
        with:
          local_build_dir: packages/sdk-core/dist/docs
          aws_region: eu-west-2
          aws_access_key_id: ${{ secrets.SITE_DEPLOYER_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.SITE_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          s3_uri: ${{ format('{0}sdk-core@{1}', secrets.SITE_DEPLOYER_AWS_S3_DOCS_URI, steps.publish-sdk-core.outputs.PUBLISHED_VERSION) }}
          cloudfront_distribution_id: E3JEO5R14CT8IH

      - name: Upload sdk-core latest documentation redirect
        if: env.PUBLISH_SDK_CORE == 1
        uses: ./build-scripts/s3cloudfront-hosting/actions/sync
        with:
          local_build_dir: sdk-core-redirect
          aws_region: eu-west-2
          aws_access_key_id: ${{ secrets.SITE_DEPLOYER_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.SITE_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          s3_uri: ${{ format('{0}sdk-core', secrets.SITE_DEPLOYER_AWS_S3_DOCS_URI) }}
          cloudfront_distribution_id: E3JEO5R14CT8IH

      - name: Build sdk-redux package
        if: env.PUBLISH_SDK_REDUX == 1
        run: |
          yarn --cwd packages/ethereum-contracts build
          yarn --cwd packages/sdk-core get-graphql-schema:v1
          yarn --cwd packages/sdk-core build
          yarn --cwd packages/sdk-redux build
          yarn --cwd packages/sdk-redux doc:html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish sdk-redux package
        id: publish-sdk-redux
        if: env.PUBLISH_SDK_REDUX == 1
        shell: bash
        run: |
          tasks/npm-publish.sh packages/sdk-redux/ latest

          PUBLISHED_VERSION=$(jq -r .version packages/sdk-redux/package.json)

          echo "PUBLISHED_VERSION=$PUBLISHED_VERSION" >> "$GITHUB_OUTPUT"

          # Create redirect from root
          mkdir sdk-redux-redirect
          printf '<!DOCTYPE html><html><head><title>Redirecting...</title><meta charset="UTF-8"><meta http-equiv="refresh" content="0;URL=%s" /><meta http-equiv="Cache-Control" content="no-store" /></head><body><p>Redirecting to latest documentation...</p></body></html>' "https://refs.superfluid.finance/sdk-redux@$PUBLISHED_VERSION" \
          > sdk-redux-redirect/index.html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload sdk-redux HTML documentation
        if: env.PUBLISH_SDK_REDUX == 1
        uses: ./build-scripts/s3cloudfront-hosting/actions/sync
        with:
          local_build_dir: packages/sdk-redux/dist/docs
          aws_region: eu-west-2
          aws_access_key_id: ${{ secrets.SITE_DEPLOYER_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.SITE_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          s3_uri: ${{ format('{0}sdk-redux@{1}', secrets.SITE_DEPLOYER_AWS_S3_DOCS_URI, steps.publish-sdk-redux.outputs.PUBLISHED_VERSION) }}
          cloudfront_distribution_id: E3JEO5R14CT8IH

      - name: Upload sdk-redux latest documentation redirect
        if: env.PUBLISH_SDK_REDUX == 1
        uses: ./build-scripts/s3cloudfront-hosting/actions/sync
        with:
          local_build_dir: sdk-redux-redirect
          aws_region: eu-west-2
          aws_access_key_id: ${{ secrets.SITE_DEPLOYER_AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.SITE_DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          s3_uri: ${{ format('{0}sdk-redux', secrets.SITE_DEPLOYER_AWS_S3_DOCS_URI) }}
          cloudfront_distribution_id: E3JEO5R14CT8IH

      - name: Build metadata package
        if: env.PUBLISH_METADATA == 1
        run: |
          yarn --cwd packages/metadata build

      - name: Publish metadata package
        if: env.PUBLISH_METADATA == 1
        shell: bash
        run: |
          tasks/npm-publish.sh packages/metadata/ latest
