name: Is PR External

on:
  pull_request:

jobs:
  check:

    runs-on: ubuntu-latest

    # Is it a PR from external repo
    if: ${{ github.event.pull_request.head.repo.full_name != 'superfluid-finance/protocol-monorepo' }}

    steps:
      - name: Show contexts
        run: |
          echo github.event_name: ${{ github.event_name }}
          echo github.sha: ${{ github.sha }}
          echo github.repository: ${{ github.repository }}
          echo github.ref: ${{ github.ref }}
          echo github.head_ref: ${{ github.head_ref }}
          echo github.base_ref: ${{ github.base_ref }}
          echo github.event.pull_request.head.repo.full_name: ${{ github.event.pull_request.head.repo.full_name }}
