name: Publish Pull Request

on:
  pull_request:
    types: [opened, ready_for_review, synchronize]

jobs:
  publish-canary:
    name: Publish PR packages to Github

    runs-on: ubuntu-latest

    if: ${{ !github.event.pull_request.draft }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      # - name: Show context
      #   run: |
      #     echo github.event_name: ${{ github.event_name }}
      #     echo github.sha: ${{ github.sha }}
      #     echo github.repository: ${{ github.repository }}
      #     echo github.ref: ${{ github.ref }}
      #     echo github.head_ref: ${{ github.head_ref }}
      #     echo github.base_ref: ${{ github.base_ref }}
      #     echo "github.event.pull_request"
      #     echo "  .number" ${{ github.event.pull_request.number }}
      #     echo "  .state" ${{ github.event.pull_request.state }}
      #     echo "  .locked" ${{ github.event.pull_request.locked }}
      #     echo "  .draft" ${{ github.event.pull_request.draft }}

      # - name: Check changeset
      #   run: tasks/check-changeset.sh ${{ github.ref }} dev
      #
      # - name: Install dependencies
      #   if: env.BUILD_ANYTHING == 1
      #   run: yarn install --frozen-lockfile
      #
      # - name: Build
      #   if: env.BUILD_ANYTHING == 1
      #   run: yarn build
      #
      # - name: Publish to github
      #   if: env.BUILD_ANYTHING == 1
      #   run: |
      #     export SHORT_REV=$(git rev-parse --short ${{ github.event.pull_request.head.sha }})
      #     export PR_NUMBER="${{ github.event.pull_request.number }}"
      #     echo "
      #     @superfluid-finance:registry=https://npm.pkg.github.com
      #     //npm.pkg.github.com/:_authToken=${SUPERFLUID_GITHUB_TOKEN}
      #     " > .npmrc
      #     ./tasks/publish-pr.sh
      #   env:
      #     SUPERFLUID_GITHUB_TOKEN: ${{ secrets.SUPERFLUID_GITHUB_TOKEN }}

      - name: Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: "github-actions[bot]"

      - name: Create comment
        # if: ${{ steps.fc.outputs.comment-id == 0 }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### 📦 PR Packages

            Install this PR by running

            ```bash
            yarn add @superfluid-finance/js-sdk@PR${{ github.event.pull_request.number }} --registry https://npm.pkg.github.com/`
            ```

            NOTE: To use the Github package registry, create a token with "read:packages" permission. See [Creating a personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) for help.

            Next add these lines to your `~/.npmrc` file, replacing TOKEN with your personal access token. See [Installing a package from Github](https://docs.github.com/en/packages/guides/configuring-npm-for-use-with-github-packages#installing-a-package) if you get stuck.

            ```
            @superfluid-finance:registry=https://npm.pkg.github.com
            //npm.pkg.github.com/:_authToken=TOKEN
            ```
