name: Publish dev branch

on:
  push:
    branches: ["dev"]

jobs:
  publish-canary:
    name: NPM publish dev branch packages
    if: github.repository == 'superfluid-finance/protocol-monorepo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/
      - name: Print node and yarn versions
        run: |
          node --version
          yarn --version
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run ESLint
        run: yarn lint
        env:
          CI: true
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
        env:
          CI: true
      - name: Publish to npm
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          echo "//registry.npmjs.org/:_authToken=${NPMJS_TOKEN}" > .npmrc
          ./tasks/publish-canary
        env:
          NPMJS_TOKEN: ${{ secrets.NPMJS_TOKEN }}
